<script setup>
import { ref } from 'vue';
import { Plus, Upload, Download, Trash2, Save, ArrowLeft, UserRound } from 'lucide-vue-next';
import { state, refresh, activate, report } from '../state.js';
import api from '../api.js';
const editor=ref(null), original=ref(''), input=ref(null), busy=ref(false);
const fields=[['description','角色描述'],['personality','性格'],['scenario','场景'],['first_mes','开场白'],['mes_example','示例对话'],['system_prompt','系统提示词'],['post_history_instructions','历史后置指令'],['creator_notes','作者备注']];
function edit(item) { original.value=item?.name || ''; const source=item ? JSON.parse(JSON.stringify(item)) : {display_name:'',traits:[],background:'',speaking_style:'',constraints:[],pet_model:''}; delete source.builtin; delete source.avatar; source.character_card=source.character_card?.data ? source.character_card : {spec:'chara_card_v2',spec_version:'2.0',data:{name:source.display_name,description:source.background || '',personality:source.traits.join('、'),first_mes:'',alternate_greetings:[],tags:[],extensions:{}}}; editor.value=source; }
async function save() { busy.value=true; try { editor.value.character_card.data.name=editor.value.display_name; if(original.value)await api.updatePersona(original.value,editor.value); else await api.createPersona(editor.value); await refresh(); editor.value=null; state.notice='角色卡已保存'; } catch(error) { report(error); } finally { busy.value=false; } }
async function upload(event) { const file=event.target.files[0]; if(!file)return; busy.value=true; try { await api.importPersona(file); await refresh(); state.notice='角色卡已导入'; } catch(error) { report(error); } finally { busy.value=false; event.target.value=''; } }
async function remove(item) { if(!confirm(`删除角色“${item.display_name}”？`))return; try { await api.deletePersona(item.name); await refresh(); } catch(error) { report(error); } }
async function select(item) { try { await activate(item.name); state.notice='已切换角色'; } catch(error) { report(error); } }
</script>
<template><section class="page-view"><header class="view-header"><div><span class="eyebrow">CHARACTERS</span><h2>{{ editor ? '编辑角色卡' : '角色库' }}</h2></div><div class="actions"><button v-if="editor" class="icon-button" title="返回角色库" @click="editor=null"><ArrowLeft :size="20"/></button><template v-else><button class="button" :disabled="busy" @click="input.click()"><Upload :size="16"/>导入</button><button class="button primary" @click="edit(null)"><Plus :size="16"/>新建</button></template><input hidden ref="input" type="file" accept=".json,.png" @change="upload"/></div></header><div class="page-body"><form v-if="editor" class="editor-form" @submit.prevent="save"><label>角色名称<input v-model="editor.display_name" required maxlength="200"/></label><label>绑定外观<select v-model="editor.pet_model"><option value="">默认外观</option><option v-for="item in state.pets" :value="item.id" :key="item.id">{{ item.name }}</option></select></label><label v-for="[key,label] in fields" :key="key">{{ label }}<textarea v-model="editor.character_card.data[key]" :rows="key==='description' ? 5 : 3"/></label><label>标签<input :value="editor.character_card.data.tags?.join(', ')" @input="editor.character_card.data.tags=$event.target.value.split(',').map(value=>value.trim()).filter(Boolean)"/></label><label>备选开场白（每行一个）<textarea :value="editor.character_card.data.alternate_greetings?.join('\n')" @input="editor.character_card.data.alternate_greetings=$event.target.value.split('\n').filter(Boolean)"/></label><button class="button primary" :disabled="busy || state.busy"><Save :size="16"/>保存角色卡</button></form><div v-else class="persona-list"><article v-for="item in state.personas" :key="item.name" class="persona-card" :class="{selected:item.name===state.config.persona_name}"><div class="persona-top"><img v-if="item.avatar" :src="item.avatar" alt="角色头像"/><div v-else class="avatar-placeholder"><UserRound :size="27"/></div><div><h3>{{ item.display_name }}</h3><span class="badge">{{ item.name===state.config.persona_name ? '当前角色' : item.builtin ? '内置角色' : '角色卡 V2' }}</span></div></div><p>{{ item.character_card?.data?.description || item.background || item.traits?.join(' · ') }}</p><div class="card-actions"><button class="button" @click="edit(item)">编辑</button><button class="button primary" :disabled="state.busy || item.name===state.config.persona_name" @click="select(item)">开始对话</button><a class="icon-button" title="导出角色卡" :href="`/api/persona/${encodeURIComponent(item.name)}/export`" download><Download :size="17"/></a><button class="icon-button" title="删除角色" :disabled="item.builtin || item.name===state.config.persona_name" @click="remove(item)"><Trash2 :size="17"/></button></div></article></div></div></section></template>
