<script setup>
import { reactive, ref, watch } from 'vue';
import { Save, Plus, KeyRound } from 'lucide-vue-next';
import { state, refresh, report } from '../state.js';
import api from '../api.js';
const form = reactive({name:'',base_url:'https://api.openai.com/v1',model:'',api_key:''});
const preferences = reactive({model_name:'',temperature:.7,max_memory_messages:20});
const busy = ref(false);
watch(() => state.config, config => Object.assign(preferences,{model_name:config.model_name,temperature:config.temperature,max_memory_messages:config.max_memory_messages}),{immediate:true});
function edit(provider) { Object.assign(form,{name:provider.name,base_url:provider.base_url || '',model:state.models.find(item=>item.provider===provider.name)?.name || '',api_key:''}); }
async function saveConnection() { busy.value=true; try { await api.saveConnection(form); form.api_key=''; await refresh(); state.notice='连接已保存'; } catch(error) { report(error); } finally { busy.value=false; } }
async function savePreferences() { busy.value=true; try { const model=state.models.find(item=>item.name===preferences.model_name); await api.updateConfig({...preferences,provider:model?.provider}); await refresh(); state.notice='模型设置已生效'; } catch(error) { report(error); } finally { busy.value=false; } }
</script>
<template><section class="page-view"><header class="view-header"><div><span class="eyebrow">CONNECTIONS</span><h2>模型与连接</h2></div><KeyRound :size="22"/></header><div class="page-body"><form class="form-section" @submit.prevent="savePreferences"><h3>当前模型</h3><label>语言模型<select v-model="preferences.model_name"><option v-for="model in state.models" :key="model.name" :value="model.name">{{ model.name }} · {{ model.provider }}</option></select></label><div class="form-grid"><label>温度 · {{ preferences.temperature }}<input v-model.number="preferences.temperature" type="range" min="0" max="2" step=".1"/></label><label>记忆消息数<input v-model.number="preferences.max_memory_messages" type="number" min="2" max="200"/></label></div><button class="button primary" :disabled="busy || state.busy"><Save :size="16"/>应用设置</button></form><section class="form-section"><h3>服务连接</h3><div class="connection-list"><button v-for="provider in state.providers" :key="provider.name" @click="edit(provider)"><span><strong>{{ provider.name }}</strong><small>{{ provider.base_url }}</small></span><span class="badge">{{ provider.has_key ? '密钥已配置' : '未配置密钥' }}</span></button></div></section><form class="form-section" @submit.prevent="saveConnection"><h3>添加 / 更新连接</h3><div class="form-grid"><label>连接名称<input v-model="form.name" required pattern="[a-zA-Z0-9_-]+" placeholder="my-provider"/></label><label>模型 ID<input v-model="form.model" required placeholder="gpt-4.1"/></label></div><label>API Base URL<input v-model="form.base_url" type="url" required/></label><label>API 密钥<input v-model="form.api_key" type="password" autocomplete="new-password" placeholder="留空保留已有密钥"/></label><button class="button primary" :disabled="busy || state.busy"><Plus :size="16"/>保存连接</button></form></div></section></template>
